name: NanoporeAnalysisEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - edlib=1.3.9
  - mappy=2.28
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pod5=0.3.12
  - pyarrow=16.1.0
  - scipy=1.13.1