name: NanoporeAnalysisEnv
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - edlib=1.3.9
  - mappy=2.28
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pip=24.0
  - pyarrow=16.1.0
  - python=3.10.14
  - scipy=1.13.1
  - pip:
      - pod5==0.3.12